#:schema node_modules/wrangler/config-schema.json
name = "wine-cellar-api"
main = "src/index.ts"
compatibility_date = "2025-11-02"

[placement]
mode = "smart"

[vars]
CF_ACCESS_TEAM = "wine-cellar"

[[d1_databases]]
binding = "DB"
database_name = "wine-cellar-api"
database_id = "08d5d178-c4f1-4be2-9906-5acea05682ae"
