#:schema node_modules/wrangler/config-schema.json
name = "wine-cellar-api"
main = "src/index.ts"
compatibility_date = "2025-11-02"

[placement]
mode = "smart"

[vars]
GITHUB_CLIENT_ID = "Ov23li1cmE2dJlzHda5X"
RP_ID = "cellar.drake.zone"
RP_ORIGIN = "https://cellar.drake.zone"

[[d1_databases]]
binding = "DB"
database_name = "wine-cellar-api"
database_id = "08d5d178-c4f1-4be2-9906-5acea05682ae"

[triggers]
crons = ["*/15 * * * *"]
